/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import java.io.*;
import java.util.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Color;

/**
 *
 * @author admin
 */
public class studentForm extends javax.swing.JFrame {

    /**
     * Creates new form studentForm
     */
    public studentForm() {
        initComponents();
        loadStudentsFromDatabase();
        addPlaceholder(searchTXT, "Student ID or Name");
        addPlaceholder(deleteTxt, "ex. 1234-1234");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        studentID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentIDtxt = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        gradetxt = new javax.swing.JTextField();
        grade = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        search = new javax.swing.JLabel();
        searchTXT = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        deleteTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        delete = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        clearXBtn2 = new javax.swing.JToggleButton();
        clearXBtn1 = new javax.swing.JToggleButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentID.setText("Student ID");
        jPanel1.add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 23, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 179, -1, -1));

        studentIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDtxtActionPerformed(evt);
            }
        });
        jPanel1.add(studentIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 20, 240, -1));

        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, -1, -1));

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 54, 240, -1));

        agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetxtActionPerformed(evt);
            }
        });
        jPanel1.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 88, 240, -1));

        age.setText("Age");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 91, -1, -1));

        gradetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradetxtActionPerformed(evt);
            }
        });
        jPanel1.add(gradetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 122, 240, -1));

        grade.setText("Grade");
        jPanel1.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 125, -1, -1));

        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Age", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 400, 120));

        search.setText("Search");
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 20));

        searchTXT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchTXT.setCaretColor(new java.awt.Color(153, 153, 153));
        searchTXT.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        searchTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTXTActionPerformed(evt);
            }
        });
        jPanel1.add(searchTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 160, -1));
        searchTXT.getAccessibleContext().setAccessibleName("");
        searchTXT.getAccessibleContext().setAccessibleDescription("");

        searchBTN.setText("search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(searchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));
        jPanel1.add(deleteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, -1));

        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, -1));

        delete.setText("Delete");
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 20));

        clearBtn.setText("clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 70, -1));

        clearXBtn2.setText("X");
        clearXBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearXBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(clearXBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 230, -1, -1));

        clearXBtn1.setText("X");
        clearXBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearXBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(clearXBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDtxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void agetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetxtActionPerformed

    private void gradetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradetxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
      // 1. Get values from text fields
        String id = studentIDtxt.getText().trim();
        String name = nametxt.getText().trim();
        String age = agetxt.getText().trim();
        String grade = gradetxt.getText().trim();

        // 2. Check for empty fields
        if (id.isEmpty() || name.isEmpty() || age.isEmpty() || grade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill out the form");
            return;
        }

        // 3. Convert age to integer only
        int ageInt;
        try {
            ageInt = Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a number");
            return;
        }

        // 4. Add to JTable
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.insertRow(0, new Object[]{id, name, ageInt, grade}); // ID as string

        // 5. Clear input fields
        studentIDtxt.setText("");
        nametxt.setText("");
        agetxt.setText("");
        gradetxt.setText("");

        // 6. Save to MySQL database
        try {
            Connection con = DBConnection.connect();
            String sql = "INSERT INTO students (student_id, name, age, grade) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id);      // ID is string now
            pst.setString(2, name);
            pst.setInt(3, ageInt);
            pst.setString(4, grade);

            pst.executeUpdate();
            con.close();

            JOptionPane.showMessageDialog(this, "Student added to database successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving to database: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTXTActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
                                               
    // Clear all input text fields
    studentIDtxt.setText("");
    nametxt.setText("");
    agetxt.setText("");
    gradetxt.setText("");
    
    // Optional: clear search and delete fields
    searchTXT.setText("Student ID or Name");
    deleteTxt.setText("ex. 1234-1234");
    
    // Optional: clear table contents
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0);
    
    // Optionally reload all students from database after clearing table
    loadStudentsFromDatabase(); 

    }//GEN-LAST:event_clearBtnActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
                                                 
    String keyword = searchTXT.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Student ID or Name to search.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // Clear table first

    try {
        Connection con = DBConnection.connect();
        String sql = "SELECT student_id, name, age, grade FROM students WHERE student_id LIKE ? OR name LIKE ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, "%" + keyword + "%");
        pst.setString(2, "%" + keyword + "%");

        java.sql.ResultSet rs = pst.executeQuery();

        boolean found = false;
        while (rs.next()) {
            found = true;
            Object[] row = {
                rs.getString("student_id"),
                rs.getString("name"),
                rs.getInt("age"),
                rs.getString("grade")
            };
            model.addRow(row);
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "No matching student found!");
        }

        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error searching: " + e.getMessage());
    }
 

    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
                                                
    String idToDelete = deleteTxt.getText().trim();

    if (idToDelete.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Student ID to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete student with ID " + idToDelete + "?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return; // user cancelled
    }

    try {
        Connection con = DBConnection.connect();
        String sql = "DELETE FROM students WHERE student_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, idToDelete);

        int rowsDeleted = pst.executeUpdate();
        con.close();

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            loadStudentsFromDatabase(); // refresh table
        } else {
            JOptionPane.showMessageDialog(this, "No student found with that ID.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting: " + e.getMessage());
    }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearXBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearXBtn1ActionPerformed
        // TODO add your handling code here:
        searchTXT.setText("");

    }//GEN-LAST:event_clearXBtn1ActionPerformed

    private void clearXBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearXBtn2ActionPerformed
        // TODO add your handling code here:
        deleteTxt.setText("");
    }//GEN-LAST:event_clearXBtn2ActionPerformed

     private void loadStudentsFromDatabase() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); // clear table

            try {
                Connection con = DBConnection.connect();
                if (con != null) {
                    String sql = "SELECT student_id, name, age, grade FROM students";
                    PreparedStatement pst = con.prepareStatement(sql);
                    java.sql.ResultSet rs = pst.executeQuery();

                    while (rs.next()) {
                        Object[] row = {
                            rs.getString("student_id"),
                            rs.getString("name"),
                            rs.getInt("age"),
                            rs.getString("grade")
                        };
                        model.addRow(row);
                    }
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading students: " + e.getMessage());
            }
        }
     private void addPlaceholder(JTextField field, String placeholder) {
        field.setText(placeholder);
        field.setForeground(Color.GRAY);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(Color.GRAY);
                }
            }
        });
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JToggleButton clearXBtn1;
    private javax.swing.JToggleButton clearXBtn2;
    private javax.swing.JLabel delete;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deleteTxt;
    private javax.swing.JLabel grade;
    private javax.swing.JTextField gradetxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel search;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField searchTXT;
    private javax.swing.JLabel studentID;
    private javax.swing.JTextField studentIDtxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
